//! OXIDE Network Daemon (networkd)
//!
//! Multi-adapter network manager service that handles:
//! - Discovery and registration of network adapters
//! - Static IP configuration from /etc/network/<iface>.conf
//! - DHCP client for dynamic IP assignment
//! - DNS server configuration in /etc/resolv.conf
//! - Adapter lifecycle management (up/down/reload)
//! - Real-time adapter state monitoring
//!
//! Config file format (/etc/network/eth0.conf):
//! ```text
//! mode=static|dhcp|manual
//! address=192.168.1.100
//! netmask=255.255.255.0
//! gateway=192.168.1.1
//! dns=8.8.8.8
//! dns=8.8.4.4
//! mtu=1500
//! ```
//!
//! Persona: ShadePacket - Networking stack engineer

#![no_std]
#![no_main]
#![allow(unused)]

extern crate alloc;

mod adapter;
mod config;
mod manager;

use alloc::string::String;
use alloc::vec::Vec;
use libc::time::usleep;
use libc::*;

use adapter::AdapterState;
use manager::AdapterManager;

/// Resolv.conf path
const RESOLV_CONF: &str = "/etc/resolv.conf";

/// Log file
const LOG_FILE: &str = "/var/log/networkd.log";

/// Poll interval (60 seconds)
const POLL_INTERVAL_US: u32 = 60_000_000;

/// Print to log file
fn log(msg: &str) {
    // ShadePacket: Dual-output logging - file and console
    let fd = open(LOG_FILE, (O_WRONLY | O_CREAT | O_APPEND) as u32, 0o644);
    if fd >= 0 {
        let prefix = b"[networkd] ";
        let _ = write(fd, prefix);
        let _ = write(fd, msg.as_bytes());
        let _ = write(fd, b"\n");
        close(fd);
    }

    prints("[networkd] ");
    prints(msg);
    prints("\n");
}

/// Write /etc/resolv.conf with DNS servers
fn write_resolv_conf(manager: &AdapterManager) {
    log("Writing /etc/resolv.conf");

    let dns_servers = manager.collect_dns_servers();

    // Create /etc directory if needed
    let _ = mkdir("/etc", 0o755);

    // Write resolv.conf
    let fd = open(RESOLV_CONF, (O_WRONLY | O_CREAT | O_TRUNC) as u32, 0o644);
    if fd < 0 {
        log("Failed to create /etc/resolv.conf");
        return;
    }

    // ShadePacket: Header for clarity
    let _ = write(fd, b"# Generated by OXIDE networkd\n");
    let _ = write(fd, b"# Do not edit manually\n\n");

    // Write nameservers
    for dns in &dns_servers {
        let _ = write(fd, b"nameserver ");
        write_ipv4(fd, dns);
        let _ = write(fd, b"\n");
    }

    close(fd);

    prints("[networkd] Wrote ");
    print_i64(dns_servers.len() as i64);
    prints(" DNS servers to /etc/resolv.conf\n");
}

/// Write IPv4 address to file descriptor
fn write_ipv4(fd: i32, addr: &[u8; 4]) {
    let mut buf = [0u8; 16];
    let mut pos = 0;

    for (i, &octet) in addr.iter().enumerate() {
        if i > 0 {
            buf[pos] = b'.';
            pos += 1;
        }
        pos += format_u8(octet, &mut buf[pos..]);
    }

    let _ = write(fd, &buf[..pos]);
}

/// Print IPv4 address to console
fn print_ipv4(addr: &[u8; 4]) {
    for (i, &octet) in addr.iter().enumerate() {
        if i > 0 {
            prints(".");
        }
        print_i64(octet as i64);
    }
}

/// Format u8 to buffer, returns length
fn format_u8(mut val: u8, buf: &mut [u8]) -> usize {
    if val == 0 {
        buf[0] = b'0';
        return 1;
    }

    let mut len = 0;
    let mut tmp = [0u8; 3];
    while val > 0 {
        tmp[len] = b'0' + (val % 10);
        val /= 10;
        len += 1;
    }

    for i in 0..len {
        buf[i] = tmp[len - 1 - i];
    }
    len
}

/// Main daemon loop
fn run_daemon() {
    log("Starting network daemon");

    // ShadePacket: Create necessary directory tree
    let _ = mkdir("/var", 0o755);
    let _ = mkdir("/var/log", 0o755);
    let _ = mkdir("/var/lib", 0o755);
    let _ = mkdir("/var/lib/dhcp", 0o755);
    let _ = mkdir("/var/lib/networkd", 0o755);
    let _ = mkdir("/etc", 0o755);
    let _ = mkdir("/etc/network", 0o755);
    let _ = mkdir("/run", 0o755);
    let _ = mkdir("/run/network", 0o755);

    // Initialize adapter manager
    let mut manager = AdapterManager::new();

    // Discover all network adapters
    manager.discover_adapters();

    // Configure all adapters from their config files
    manager.configure_all();

    // Write resolv.conf with collected DNS servers
    write_resolv_conf(&manager);

    log("Network configuration complete");

    // ShadePacket: Main monitoring loop - check for changes periodically
    loop {
        usleep(POLL_INTERVAL_US);

        // Update all adapter statistics
        manager.update_all_stats();

        // TODO: Check for DHCP lease renewal
        // TODO: Monitor for interface hotplug events
        // TODO: Detect link state changes
    }
}

/// Show usage
fn show_usage() {
    prints("Usage: networkd [command]\n");
    prints("\n");
    prints("Commands:\n");
    prints("  daemon        Run as daemon (started by init/servicemgr)\n");
    prints("  status        Show network status for all adapters\n");
    prints("  list          List all network adapters\n");
    prints("  up <iface>    Bring network adapter up\n");
    prints("  down <iface>  Bring network adapter down\n");
    prints("  reload [iface] Reload configuration (all or specific adapter)\n");
    prints("  config <iface> Show adapter configuration\n");
    prints("  help          Show this help\n");
}

/// Show network status for all adapters
fn show_status() {
    prints("Network Status:\n\n");

    let mut manager = AdapterManager::new();
    manager.discover_adapters();

    for adapter in manager.get_all_adapters() {
        prints(&adapter.name);
        prints(":\n");
        
        // State
        prints("  State: ");
        match adapter.state {
            AdapterState::Down => prints("DOWN"),
            AdapterState::Configuring => prints("CONFIGURING"),
            AdapterState::Up => prints("UP"),
            AdapterState::Error => prints("ERROR"),
            AdapterState::Removing => prints("REMOVING"),
        }
        prints("\n");

        // Link status
        prints("  Link: ");
        if adapter.link_up {
            prints("UP");
        } else {
            prints("DOWN");
        }
        prints("\n");

        // MAC address
        prints("  MAC: ");
        for (i, &byte) in adapter.mac.iter().enumerate() {
            if i > 0 {
                prints(":");
            }
            print_hex_byte(byte);
        }
        prints("\n");

        // IPv4 address
        if let Some(addr) = adapter.ipv4_addr {
            prints("  IPv4: ");
            print_ipv4(&addr);
            if let Some(netmask) = adapter.ipv4_netmask {
                prints(" / ");
                print_ipv4(&netmask);
            }
            prints("\n");
        }

        // Gateway
        if let Some(gateway) = adapter.ipv4_gateway {
            prints("  Gateway: ");
            print_ipv4(&gateway);
            prints("\n");
        }

        // DNS
        if !adapter.dns_servers.is_empty() {
            prints("  DNS: ");
            for (i, dns) in adapter.dns_servers.iter().enumerate() {
                if i > 0 {
                    prints(", ");
                }
                print_ipv4(dns);
            }
            prints("\n");
        }

        // Statistics
        prints("  RX: ");
        print_i64(adapter.rx_packets as i64);
        prints(" packets, ");
        print_i64(adapter.rx_bytes as i64);
        prints(" bytes\n");

        prints("  TX: ");
        print_i64(adapter.tx_packets as i64);
        prints(" packets, ");
        print_i64(adapter.tx_bytes as i64);
        prints(" bytes\n");

        prints("\n");
    }
}

/// List all network adapters
fn list_adapters() {
    let mut manager = AdapterManager::new();
    manager.discover_adapters();

    prints("Network Adapters:\n\n");
    prints("NAME     STATE        LINK    ADDRESS\n");
    prints("----------------------------------------------\n");

    for adapter in manager.get_all_adapters() {
        // Name (padded to 8 chars)
        prints(&adapter.name);
        for _ in 0..(9 - adapter.name.len().min(8)) {
            prints(" ");
        }

        // State (padded to 12 chars)
        let state_str = match adapter.state {
            AdapterState::Down => "DOWN",
            AdapterState::Configuring => "CONFIGURING",
            AdapterState::Up => "UP",
            AdapterState::Error => "ERROR",
            AdapterState::Removing => "REMOVING",
        };
        prints(state_str);
        for _ in 0..(13 - state_str.len()) {
            prints(" ");
        }

        // Link
        if adapter.link_up {
            prints("UP      ");
        } else {
            prints("DOWN    ");
        }

        // Address
        if let Some(addr) = adapter.ipv4_addr {
            print_ipv4(&addr);
        } else {
            prints("(none)");
        }

        prints("\n");
    }
}

/// Show adapter configuration
fn show_config(iface_name: &str) {
    let mut manager = AdapterManager::new();
    manager.discover_adapters();

    if let Some(adapter) = manager.get_adapter(iface_name) {
        prints("Configuration for ");
        prints(iface_name);
        prints(":\n\n");

        prints("  Mode: ");
        match adapter.mode {
            adapter::ConfigMode::Static => prints("Static"),
            adapter::ConfigMode::Dhcp => prints("DHCP"),
            adapter::ConfigMode::Manual => prints("Manual"),
            adapter::ConfigMode::Loopback => prints("Loopback"),
        }
        prints("\n");

        if let Some(addr) = adapter.ipv4_addr {
            prints("  Address: ");
            print_ipv4(&addr);
            prints("\n");
        }

        if let Some(netmask) = adapter.ipv4_netmask {
            prints("  Netmask: ");
            print_ipv4(&netmask);
            prints("\n");
        }

        if let Some(gateway) = adapter.ipv4_gateway {
            prints("  Gateway: ");
            print_ipv4(&gateway);
            prints("\n");
        }

        prints("  MTU: ");
        print_i64(adapter.mtu as i64);
        prints("\n");

        if !adapter.dns_servers.is_empty() {
            prints("  DNS Servers:\n");
            for dns in &adapter.dns_servers {
                prints("    ");
                print_ipv4(dns);
                prints("\n");
            }
        }
    } else {
        prints("Adapter not found: ");
        prints(iface_name);
        prints("\n");
    }
}

/// Bring adapter up
fn adapter_up(iface_name: &str) {
    let mut manager = AdapterManager::new();
    manager.discover_adapters();

    if manager.bring_up(iface_name) {
        prints("Brought up ");
        prints(iface_name);
        prints("\n");

        // Update resolv.conf
        write_resolv_conf(&manager);
    } else {
        prints("Failed to bring up ");
        prints(iface_name);
        prints("\n");
    }
}

/// Bring adapter down
fn adapter_down(iface_name: &str) {
    let mut manager = AdapterManager::new();
    manager.discover_adapters();

    if manager.bring_down(iface_name) {
        prints("Brought down ");
        prints(iface_name);
        prints("\n");

        // Update resolv.conf
        write_resolv_conf(&manager);
    } else {
        prints("Failed to bring down ");
        prints(iface_name);
        prints("\n");
    }
}

/// Reload adapter configuration
fn reload_config(iface_name: Option<&str>) {
    let mut manager = AdapterManager::new();
    manager.discover_adapters();

    if let Some(name) = iface_name {
        // Reload specific adapter
        if manager.reload_adapter(name) {
            prints("Reloaded configuration for ");
            prints(name);
            prints("\n");
        } else {
            prints("Failed to reload ");
            prints(name);
            prints("\n");
        }
    } else {
        // Reload all adapters
        log("Reloading all adapter configurations");
        manager.configure_all();
    }

    // Update resolv.conf
    write_resolv_conf(&manager);
}

/// Print a byte as hex
fn print_hex_byte(byte: u8) {
    let high = (byte >> 4) & 0x0F;
    let low = byte & 0x0F;
    
    print_hex_nibble(high);
    print_hex_nibble(low);
}

/// Print a hex nibble
fn print_hex_nibble(nibble: u8) {
    if nibble < 10 {
        let c = (b'0' + nibble) as char;
        prints(core::str::from_utf8(&[c as u8]).unwrap_or("?"));
    } else {
        let c = (b'a' + (nibble - 10)) as char;
        prints(core::str::from_utf8(&[c as u8]).unwrap_or("?"));
    }
}

/// Main entry point
#[unsafe(no_mangle)]
fn main(argc: i32, argv: *const *const u8) -> i32 {
    let cmd = if argc >= 2 {
        cstr_to_str(unsafe { *argv.add(1) })
    } else {
        "daemon"
    };

    match cmd {
        "daemon" => {
            run_daemon();
            0
        }
        "status" => {
            show_status();
            0
        }
        "list" => {
            list_adapters();
            0
        }
        "up" => {
            if argc >= 3 {
                let iface = cstr_to_str(unsafe { *argv.add(2) });
                adapter_up(iface);
                0
            } else {
                prints("Error: Missing interface name\n");
                prints("Usage: networkd up <interface>\n");
                1
            }
        }
        "down" => {
            if argc >= 3 {
                let iface = cstr_to_str(unsafe { *argv.add(2) });
                adapter_down(iface);
                0
            } else {
                prints("Error: Missing interface name\n");
                prints("Usage: networkd down <interface>\n");
                1
            }
        }
        "reload" => {
            let iface = if argc >= 3 {
                Some(cstr_to_str(unsafe { *argv.add(2) }))
            } else {
                None
            };
            reload_config(iface);
            0
        }
        "config" => {
            if argc >= 3 {
                let iface = cstr_to_str(unsafe { *argv.add(2) });
                show_config(iface);
                0
            } else {
                prints("Error: Missing interface name\n");
                prints("Usage: networkd config <interface>\n");
                1
            }
        }
        "help" | "--help" | "-h" => {
            show_usage();
            0
        }
        _ => {
            prints("Unknown command: ");
            prints(cmd);
            prints("\n");
            show_usage();
            1
        }
    }
}

/// Convert C string to str
fn cstr_to_str(ptr: *const u8) -> &'static str {
    if ptr.is_null() {
        return "";
    }
    let mut len = 0;
    unsafe {
        while *ptr.add(len) != 0 {
            len += 1;
        }
        core::str::from_utf8_unchecked(core::slice::from_raw_parts(ptr, len))
    }
}
