[package]
name = "procfs"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Process filesystem for OXIDE OS"

[dependencies]
vfs = { workspace = true }
proc = { workspace = true }
proc-traits = { workspace = true }
os_core = { workspace = true }
spin = { workspace = true }
sched = { workspace = true }
mm-vmstat = { workspace = true }
mm-pagedb = { workspace = true }
mm-core = { workspace = true }
mm-manager = { workspace = true }
mm-vma = { workspace = true }
mm-swap = { workspace = true }
mm-reclaim = { workspace = true }
mm-pagecache = { workspace = true }
